#%RAML 1.0 NamedExample
value:
  firstName: "Gonzalo"
  lastName: "Marcos"
  email: "gmarcos@salesforce.com"
  phone: "444-555-111"
  birthdate: "16/05/1981"
  mailingAddress:
    street: "Via Cesare Balbo 2"
    city: "Torino"
    state: "Piemonte"
    postalCode: "56788"
    country: "Italy"
  